root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
delay = 1000                                              # ms
kill_delay = "0s"
exclude_dir = ["tmp", "node_modules", "assets", "global"]
include_ext = ["go", "html"]
exclude_regex = ["_test\\.go"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
